### ISSUE TITLE
Fortnite replay reader

### ISSUE THREAD

**Issue by fredimachado** [UppyMeister/FortniteReplayRepairer#1]
Hey Thomas,

I saw your repo and I think you might be interested in my  .net core replay reader project at https://github.com/fredimachado/FortniteReplayReader

Sorry, I created this issue because I didn't know other way to contact you.

Cheers!

**Comment by tomupson** [comment]
Hi Fredi,

Sorry for the super late reply, I had no idea anyone even knew about this repo!
Your project looks awesome, I can't believe I didn't even think about implementing it in my application.

It's awesome how such a small little program can provide the means for a potentially much larger application. I can see so many ways how it could be expanded to a proper replay replayer.

Thanks,

Tom
